ALTER TABLE "Orders" ADD COLUMN "positionType" "PositionType" NOT NULL DEFAULT 'LONG';
ALTER TABLE "Orders" ADD COLUMN "remainingQty" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Fills" ADD COLUMN "price" DOUBLE PRECISION NOT NULL DEFAULT 0;

INSERT INTO "Markets" ("id", "symbol", "market", "maxLeverage")
VALUES
  ('BTCUSDT', 'BTCUSDT', 'BTC/USDT', 100),
  ('ETHUSDT', 'ETHUSDT', 'ETH/USDT', 100),
  ('SOLUSDT', 'SOLUSDT', 'SOL/USDT', 100)
ON CONFLICT ("id") DO NOTHING;
